/* empty css                      */import{a as q,S as M,i}from"./assets/vendor-BNsGcbod.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function c(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(e){if(e.ep)return;e.ep=!0;const s=c(e);fetch(e.href,s)}})();async function P(o,t){return(await q.get("https://pixabay.com/api/",{params:{key:"50913402-008034d842f29df0686066032",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:40,page:t}})).data}const h=document.querySelector("#search-form"),p=document.querySelector(".gallery"),y=document.querySelector(".loader"),L=document.querySelector(".loading-message"),m=document.querySelector("#load-more"),E=new M(".gallery a"),v=document.querySelector("#loading-message-bottom");let a=1,d="",r=[],g=0;function B(o){const t=Math.floor(o.length/3)*3,n=o.slice(0,t).map(e=>`
      <a href="${e.largeImageURL}" class="gallery-item">
        <img src="${e.webformatURL}" alt="${e.tags}" />
        <div class="info">
          <div class="info-block"><span class="info-title">Likes</span><span class="info-value">${e.likes}</span></div>
          <div class="info-block"><span class="info-title">Views</span><span class="info-value">${e.views}</span></div>
          <div class="info-block"><span class="info-title">Comments</span><span class="info-value">${e.comments}</span></div>
          <div class="info-block"><span class="info-title">Downloads</span><span class="info-value">${e.downloads}</span></div>
        </div>
      </a>
    `).join("");return p.insertAdjacentHTML("beforeend",n),E.refresh(),o.slice(t)}function I(){v.classList.remove("hidden")}function R(){v.classList.add("hidden")}function T(){L.classList.remove("hidden")}function $(){setTimeout(()=>{L.classList.add("hidden")},1e3)}function w(){y.classList.remove("hidden")}function u(){y.classList.add("hidden")}function b(){m.classList.add("visible")}function f(){m.classList.remove("visible")}async function S(o){a===1&&(p.innerHTML="",r=[]),w(),T();try{const t=await P(o,a);if(u(),$(),t.hits.length===0){i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#EF4040"}),f();return}g=t.totalHits,r=r.concat(t.hits),r=B(r),r.length===0&&a*40>=g?(f(),i.info("You've reached the end of the search results.")):b()}catch(t){u(),i.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(t)}}h.addEventListener("submit",o=>{o.preventDefault();const t=o.target.searchQuery.value.trim();t&&(d=t,a=1,S(d),h.reset())});m.addEventListener("click",async()=>{f(),I(),w(),await new Promise(o=>setTimeout(o,2e3)),a+=1;try{await S(d);const o=document.querySelector(".gallery-item");if(o){const{height:t}=o.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}}catch{i.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{R(),u(),b()}});
//# sourceMappingURL=index.js.map
